apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_SLUG__-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
  - secretName: stagingapps.net
  rules:
  - host: __URL_STAGING__
    http:
      paths:
      - path: /
        backend:
          serviceName: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_SLUG__
          servicePort: 80

